name: release build

on:
  release:
    types:
      - published

jobs:

  build_windows:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: "3.8"

    - name: Install dependencies
      shell: powershell
      run: |
          python -m pip install --upgrade pip
          python -m pip install pyqt5 pyinstaller

    - name: build with pyinstaller
      shell: powershell
      run: |
        pyuic5 -o .\rm102\mainwindow.py mainwindow.ui
        pyuic5 -o .\rm102\help_dialog.py help_dialog.ui
        pyinstaller --noconsole --onefile .\bin\rm102

    - name: upload exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: rm102_windows
        path: dist/rm102.exe

  build_macos:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: "3.8"

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install pyqt5 pyinstaller

    - name: build with pyinstaller
      run: |
        pyuic5 -o ./rm102/mainwindow.py mainwindow.ui
        pyuic5 -o ./rm102/help_dialog.py help_dialog.ui
        pyinstaller --noconsole --onefile ./bin/rm102
        mv ./dist/rm102 ./dist/rm102.macos

    - name: upload binary
      uses: actions/upload-artifact@v2
      with:
        name: rm102_macos
        path: dist/rm102.macos

  build_linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: "3.8"

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install pyqt5 pyinstaller

    - name: build with pyinstaller
      run: |
        pyuic5 -o ./rm102/mainwindow.py mainwindow.ui
        pyuic5 -o ./rm102/help_dialog.py help_dialog.ui
        pyinstaller --onefile ./bin/rm102
        mv ./dist/rm102 ./dist/rm102.run

    - name: upload binary
      uses: actions/upload-artifact@v2
      with:
        name: rm102_linux
        path: dist/rm102.run

  upload_all:    # separate job on Ubuntu since JasonEtco/upload-to-release@master only runs on Linux

    needs: [build_windows, build_macos, build_linux]

    runs-on: ubuntu-latest

    steps:

    - name: download exe
      uses: actions/download-artifact@v2

    - name: upload exe to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: rm102_windows/rm102.exe application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    # token generated implicitly

    - name: upload mac binary to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: rm102_macos/rm102.macos application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    # token generated implicitly

    - name: upload binary to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: rm102_linux/rm102.run application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    # token generated implicitly
